- read analysis data from analysis.json
windup/windup_ide_tests pull request #25
Opened 2023-03-09 12:33 UTC by midays

Signed-off by midays@redhat.com

2023-03-09 12:34 UTC, midays commented
- Dynamically create test runs
- update config file name
- add open_report_page

2023-03-09 20:36 UTC, sshveta requested changes
Looks good @midays Few changes required.

2023-03-09 20:36 UTC, sshveta commented on src/tests/test_analysis_intellij.py
> +def test_analysis_eap(setup_intellij, app_name, analysis_data):
We can change the name of this test to 
 "test_different_analysis"  As it is running analysis on various targets and sources .

2023-03-09 20:36 UTC, sshveta commented on src/tests/test_analysis_intellij.py
> +    Analysis tests for VScode using various migration paths
This is for intelliJ right??

2023-03-12 08:59 UTC, midays commented on src/tests/test_analysis_intellij.py
> +    Analysis tests for VScode using various migration paths
done

2023-03-12 09:00 UTC, midays commented on src/tests/test_analysis_intellij.py
> +def test_analysis_eap(setup_intellij, app_name, analysis_data):
done, changed naming to **test_analysis_intellij** to match up with **test_analysis_vscode**

2023-03-14 14:22 UTC, nachandr approved these changes
LGTM

2023-03-14 14:29 UTC, sshveta approved these changes

2023-03-14 14:29 UTC, merged