[WIP] updated readme file
windup/windup_ide_tests pull request #43
Opened 2023-08-13 12:53 UTC by midays

2023-08-15 13:37 UTC, nachandr commented on README.md
> +    `pip install opencv-python`
This could go in the requirements.txt  file.

2023-08-22 15:23 UTC, sshveta requested changes

2023-08-22 15:23 UTC, sshveta commented on README.md
> +- JDK 11 installed, if there are multiple JDK version installed on the system, make sure JDK 11 is set as the default default
default two times

2023-08-22 15:23 UTC, nachandr approved these changes
LGTM !

2023-08-22 15:30 UTC, sshveta approved these changes

2023-08-22 15:30 UTC, merged